from .locatable import Locatable
from .movable import Movable
from .player_controllable import PlayerControllable
from .frog import Frog
from .dodgeable import Dodgeable
from .race_car import RaceCar
from .dozer import Dozer
from .truck import Truck
from .car import Car
from .rideable import Rideable
from .log import Log
from .turtle import Turtle
from .alligator import Alligator
from .immovable import Immovable
from .touchable import Touchable
from .home import Home
from .stage import Stage
from .road import Road
from .untouchable import Untouchable
from .water import Water
from .grass import Grass
